(function(){
  const frame=document.getElementById('app'); if(!frame)return;
  const pad=n=>String(n).padStart(2,'0');
  const parseDate=s=>{const m=String(s||'').match(/^(\d{2})\/(\d{2})\/(\d{4})$/);return m?new Date(+m[3],+m[2]-1,+m[1]):null};
  const fmtDate=d=>pad(d.getDate())+'/'+pad(d.getMonth()+1)+'/'+d.getFullYear();
  const inputDate=s=>{const d=parseDate(s);return d?d.getFullYear()+'-'+pad(d.getMonth()+1)+'-'+pad(d.getDate()):''};
  const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
  const normalizeTime=value=>{let s=String(value||'').trim().toUpperCase().replace(/H/g,'').replace(/\s/g,'');if(!s)return '';let h,m;if(s.includes(':')){const p=s.split(':');h=p[0];m=p[1]||'00'}else if(/^\d{1,2}$/.test(s)){h=s;m='00'}else if(/^\d{3,4}$/.test(s)){h=s.length===3?s.slice(0,1):s.slice(0,-2);m=s.slice(-2)}else return String(value||'');h=Number(h);m=Number(m);return Number.isInteger(h)&&Number.isInteger(m)&&h>=0&&h<=23&&m>=0&&m<=59?pad(h)+':'+pad(m)+'H':String(value||'')};
  const monthText=d=>new Intl.DateTimeFormat('pt-BR',{month:'long',year:'numeric'}).format(d).replace(/^./,c=>c.toUpperCase());
  function boot(){
    let w,d,store;
    try{w=frame.contentWindow;d=frame.contentDocument;store=w.eval('data')}catch(e){return}
    if(!w||!d||!store||!d.getElementById('main'))return;
    if(!d.getElementById('rhpro-agenda-style')){const st=d.createElement('style');st.id='rhpro-agenda-style';st.textContent='.rhpro-agenda-bar{display:flex;align-items:center;justify-content:center;gap:8px;flex-wrap:wrap;margin-bottom:14px}.rhpro-agenda-bar .month{font-size:22px;font-weight:800;color:#123b67;min-width:230px;text-align:center}.rhpro-agenda-info{font-size:13px;color:#6b7280;margin:0 0 12px}.rhpro-agenda-empty{padding:32px;text-align:center;color:#6b7280}.rhpro-agenda-time-note{font-size:11px;color:#6b7280;font-weight:400;margin-top:4px}.rhpro-agenda-nowrap th,.rhpro-agenda-nowrap td{white-space:nowrap;word-break:normal;overflow-wrap:normal}@media(max-width:700px){.rhpro-agenda-bar .month{order:-1;flex-basis:100%}.rhpro-agenda-bar button{flex:1}}';d.head.appendChild(st)}
    let month=w.__RHPRO_AGENDA_MONTH||new Date(new Date().getFullYear(),new Date().getMonth(),1);w.__RHPRO_AGENDA_MONTH=month;
    const rows=()=> (store['Agenda RH']||[]).map((r,i)=>({r,i,d:parseDate(r[0])})).filter(x=>x.d&&x.d.getFullYear()===month.getFullYear()&&x.d.getMonth()===month.getMonth()).sort((a,b)=>a.d-b.d||normalizeTime(a.r[1]).localeCompare(normalizeTime(b.r[1])));
    function render(){const main=d.getElementById('main');if(!main)return;const list=rows(),total=(store['Agenda RH']||[]).length;main.innerHTML='<div class="top"><div><h1>📅 Agenda RH</h1><div class="muted">Compromissos organizados por mês.</div></div></div><div class="panel"><div class="rhpro-agenda-bar"><button id="rh-ag-prev" class="secondary" type="button">‹ Mês anterior</button><button id="rh-ag-today" class="secondary" type="button">Hoje</button><div class="month">'+esc(monthText(month))+'</div><button id="rh-ag-next" class="secondary" type="button">Próximo mês ›</button><button id="rh-ag-new" class="primary" type="button">+ Novo compromisso</button></div><div class="rhpro-agenda-info">Mostrando '+list.length+' compromisso(s) de '+esc(monthText(month))+'. Total cadastrado: '+total+'.</div><div class="actions"><input id="rh-ag-search" class="search" placeholder="Pesquisar neste mês..."></div><div class="table-wrap"><table class="rhpro-agenda-nowrap"><thead><tr><th>Data</th><th>Hora</th><th>Evento</th><th>Descrição</th><th>Participantes</th><th>Local</th><th>Status</th><th>Observações</th><th>Ações</th></tr></thead><tbody id="rh-ag-body"></tbody></table></div></div>';const body=d.getElementById('rh-ag-body');function table(){const q=(d.getElementById('rh-ag-search').value||'').toLowerCase().trim();const a=rows().filter(x=>x.r.join(' ').toLowerCase().includes(q));body.innerHTML=a.length?a.map(x=>'<tr><td><b>'+esc(x.r[0])+'</b></td><td>'+esc(normalizeTime(x.r[1]))+'</td><td>'+esc(x.r[2])+'</td><td>'+esc(x.r[3])+'</td><td>'+esc(x.r[4])+'</td><td>'+esc(x.r[5])+'</td><td>'+esc(x.r[6])+'</td><td>'+esc(x.r[7])+'</td><td><button class="mini" data-edit="'+x.i+'">Editar</button><button class="mini" data-del="'+x.i+'">Excluir</button></td></tr>').join(''):'<tr><td colspan="9"><div class="rhpro-agenda-empty">Nenhum compromisso cadastrado neste mês.</div></td></tr>'}table();d.getElementById('rh-ag-search').oninput=table;d.getElementById('rh-ag-prev').onclick=()=>{month=new Date(month.getFullYear(),month.getMonth()-1,1);w.__RHPRO_AGENDA_MONTH=month;render()};d.getElementById('rh-ag-next').onclick=()=>{month=new Date(month.getFullYear(),month.getMonth()+1,1);w.__RHPRO_AGENDA_MONTH=month;render()};d.getElementById('rh-ag-today').onclick=()=>{const n=new Date();month=new Date(n.getFullYear(),n.getMonth(),1);w.__RHPRO_AGENDA_MONTH=month;render()};d.getElementById('rh-ag-new').onclick=()=>form(-1);body.onclick=e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.edit!==undefined)form(Number(b.dataset.edit));if(b.dataset.del!==undefined&&confirm('Excluir este compromisso?')){store['Agenda RH'].splice(Number(b.dataset.del),1);if(typeof w.save==='function')w.save();render()}}}
    function form(index){const old=index<0?Array(8).fill(''):(store['Agenda RH']||[])[index]||Array(8).fill('');const names=['Data','Hora','Evento','Descrição','Participantes','Local','Status','Observações'];let html='<div class="top"><div><h1>'+(index<0?'Novo':'Editar')+' — Agenda RH</h1><div class="muted">Digite somente o número no horário: 9 → 09:00H • 930 → 09:30H • 14 → 14:00H.</div></div></div><div class="panel"><div class="grid">';names.forEach((name,i)=>{if(i===0)html+='<label>'+name+'<input id="rh-ag-f0" type="date" value="'+esc(inputDate(old[0]))+'"></label>';else if(i===1)html+='<label>'+name+'<input id="rh-ag-f1" inputmode="numeric" autocomplete="off" placeholder="9 ou 930" value="'+esc(normalizeTime(old[1]))+'"><div class="rhpro-agenda-time-note">9 → 09:00H | 930 → 09:30H | 14 → 14:00H</div></label>';else if(i===6)html+='<label>'+name+'<select id="rh-ag-f6">'+['Agendado','Confirmado','Em andamento','Concluído','Cancelado'].map(o=>'<option '+((old[6]||'Agendado')===o?'selected':'')+'>'+o+'</option>').join('')+'</select></label>';else html+='<label>'+name+'<input id="rh-ag-f'+i+'" value="'+esc(old[i]||'')+'"></label>'});html+='</div><div class="actions" style="margin-top:18px"><button id="rh-ag-save" class="primary" type="button">Salvar compromisso</button><button id="rh-ag-cancel" class="secondary" type="button">Cancelar</button></div></div>';d.getElementById('main').innerHTML=html;d.getElementById('rh-ag-f1').onblur=function(){const t=normalizeTime(this.value);if(t)this.value=t};d.getElementById('rh-ag-save').onclick=()=>{const r=names.map((_,i)=>d.getElementById('rh-ag-f'+i)?.value||'');if(!r[0])return alert('Informe a data.');const t=normalizeTime(r[1]);if(r[1]&&!/^\d{2}:\d{2}H$/.test(t))return alert('Horário inválido. Use 9, 930 ou 14:30.');const z=new Date(r[0]+'T00:00:00');r[0]=fmtDate(z);r[1]=t;store['Agenda RH']=store['Agenda RH']||[];if(index<0)store['Agenda RH'].push(r);else store['Agenda RH'][index]=r;if(typeof w.save==='function')w.save();month=new Date(z.getFullYear(),z.getMonth(),1);w.__RHPRO_AGENDA_MONTH=month;render()};d.getElementById('rh-ag-cancel').onclick=render}
    if(!w.__RHPRO_AGENDA_WRAPPED&&typeof w.showSection==='function'){const old=w.showSection;w.showSection=function(n){const r=old.apply(this,arguments);if(String(n||'')==='Agenda RH')setTimeout(render,120);return r};w.__RHPRO_AGENDA_WRAPPED=true}
    if(!w.__RHPRO_AGENDA_CLICK_LISTENER){d.addEventListener('click',e=>{let el=e.target;while(el&&el!==d.body){if(String(el.textContent||'').trim()==='Agenda RH'){setTimeout(render,180);break}el=el.parentElement}},true);w.__RHPRO_AGENDA_CLICK_LISTENER=true}
    const title=String(d.querySelector('h1')?.textContent||'').trim();
    if((title==='Agenda RH' || title==='📅 Agenda RH') && !d.getElementById('rh-ag-f0') && !d.getElementById('rh-ag-save')){
      if(!d.getElementById('rh-ag-prev'))render();
    }
  }
  frame.addEventListener('load',()=>{setTimeout(boot,100);setTimeout(boot,800);setTimeout(boot,2000)});setTimeout(boot,500);setTimeout(boot,2000);setTimeout(boot,5000);setInterval(boot,1500);
})();