const CLOUD_SUPABASE_URL='https://ydqqxvtfvnhxpydccciu.supabase.co';
const CLOUD_SUPABASE_KEY='sb_publishable_A-x4W6e_ES8k7fQR3TgGhw_DeVLH50O';
const cloudDb=window.supabase.createClient(CLOUD_SUPABASE_URL,CLOUD_SUPABASE_KEY);
const CLOUD_DATABASES=['RH_PRO_DOCUMENTOS','RH_PRO_TREINAMENTOS'];
let cloudUser=null,cloudBusy=false,cloudTimer=null;
const cloudStatus=msg=>{const el=document.getElementById('sync');if(el&&msg)el.textContent=msg;};
function openLocalFilesDB(name='RH_PRO_DOCUMENTOS',mode='readonly'){return new Promise((resolve,reject)=>{const req=indexedDB.open(name);req.onupgradeneeded=()=>{if(!req.result.objectStoreNames.contains('files'))req.result.createObjectStore('files',{keyPath:'id'});};req.onsuccess=()=>{const db=req.result;if(!db.objectStoreNames.contains('files')){db.close();reject(new Error('Armazenamento indisponível.'));return;}try{const tx=db.transaction('files',mode);resolve({db,tx,store:tx.objectStore('files')});}catch(e){db.close();reject(e);}};req.onerror=()=>reject(req.error||new Error('Não foi possível abrir documentos locais.'));});}
async function allLocalFiles(name){try{const {db,store}=await openLocalFilesDB(name,'readonly');return await new Promise(resolve=>{const r=store.getAll();r.onsuccess=()=>{const out=r.result||[];db.close();resolve(out);};r.onerror=()=>{db.close();resolve([]);};});}catch(e){console.error('RH PRO local files',name,e);return[];}}
async function putLocalFile(name,rec){if(!rec?.id||!rec?.blob)return false;try{const {db,tx,store}=await openLocalFilesDB(name,'readwrite');return await new Promise(resolve=>{store.put(rec);tx.oncomplete=()=>{db.close();resolve(true);};tx.onerror=()=>{db.close();resolve(false);};tx.onabort=()=>{db.close();resolve(false);};});}catch(e){console.error('RH PRO write local file',name,e);return false;}}
function databaseForFile(storagePath=''){return String(storagePath||'').includes('RH_PRO_TREINAMENTOS')?'RH_PRO_TREINAMENTOS':'RH_PRO_DOCUMENTOS';}
function isFileName(name=''){return /\.(pdf|jpg|jpeg|png|gif|webp|doc|docx|xls|xlsx|txt|csv|zip)$/i.test(String(name||''));}
async function valueToBlob(value,mimeType='application/octet-stream'){try{if(value instanceof Blob)return value;if(value instanceof File)return value;if(typeof value!=='string')return null;const s=value.trim();if(/^data:/i.test(s)){const m=s.match(/^data:([^;,]+)?(;base64)?,(.*)$/i);if(!m)return null;const mime=m[1]||mimeType;const body=m[3]||'';const bin=m[2]?atob(body):decodeURIComponent(body);const bytes=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)bytes[i]=bin.charCodeAt(i);return new Blob([bytes],{type:mime});}return null;}catch(e){return null;}}
function normalizeFileRecord(rec,sourceDb='',sourceStore=''){if(!rec||typeof rec!=='object')return null;const name=String(rec.fileName||rec.filename||rec.nome||rec.name||rec.file_name||rec.arquivo||rec.documento||'').trim();let id=String(rec.id||rec.fileId||rec.file_id||rec.documentId||rec.document_id||'').trim();let raw=rec.blob||rec.file||rec.arquivoBlob||rec.fileBlob||rec.dataUrl||rec.dataURL||rec.base64||rec.content||null;let mime=rec.mimeType||rec.mime_type||rec.type||'';if(!id&&name)id='legacy_'+btoa(unescape(encodeURIComponent(sourceDb+'|'+sourceStore+'|'+name))).replace(/[^a-zA-Z0-9_-]/g,'').slice(0,80);if(!name||!isFileName(name)||!raw)return null;return {id,blob:raw,fileName:name,nome:name,mimeType:mime||null,sourceDb,sourceStore};}
async function readStoreAll(db,storeName){return await new Promise(resolve=>{try{const tx=db.transaction(storeName,'readonly'),store=tx.objectStore(storeName),r=store.getAll();r.onsuccess=()=>resolve(r.result||[]);r.onerror=()=>resolve([]);}catch(e){resolve([]);}});}
async function discoverIndexedDbFiles(){const out=[];try{if(typeof indexedDB.databases!=='function')return out;const dbs=await indexedDB.databases();for(const info of dbs||[]){const name=String(info?.name||'');if(!name)continue;let db=null;try{db=await new Promise((resolve,reject)=>{const req=indexedDB.open(name);req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error);});for(const storeName of [...db.objectStoreNames]){const rows=await readStoreAll(db,storeName);for(const rec of rows){const n=normalizeFileRecord(rec,name,storeName);if(n){const b=await valueToBlob(n.blob,n.mimeType);if(b)n.blob=b;else continue;out.push(n);}}}}catch(e){console.warn('RH PRO legacy IndexedDB scan',name,e);}finally{try{db?.close();}catch(e){}}}}catch(e){console.warn('RH PRO IndexedDB discovery',e);}return out;}
function collectFileCandidates(value,source='localStorage',seen=new Set(),out=[]){if(value==null)return out;if(typeof value==='object'){if(seen.has(value))return out;seen.add(value);const n=normalizeFileRecord(value,source,'storage');if(n)out.push(n);for(const k of Object.keys(value)){if(out.length>500)break;const v=value[k];if(v&&typeof v==='object')collectFileCandidates(v,source,seen,out);}}return out;}
async function discoverWebStorageFiles(){const out=[];for(const storage of [window.localStorage,window.sessionStorage]){try{for(let i=0;i<storage.length;i++){const key=storage.key(i)||'';if(!/file|doc|ferias|rhdp|trein|relatorio/i.test(key))continue;const raw=storage.getItem(key);if(!raw||raw.length<30)continue;try{collectFileCandidates(JSON.parse(raw),key,new Set(),out);}catch(e){}}}catch(e){console.warn('RH PRO web storage scan',e);}}return out;}
async function discoverAllLocalFiles(){const a=await discoverIndexedDbFiles(),b=await discoverWebStorageFiles(),map=new Map();for(const f of [...a,...b]){if(!f?.id||!f?.blob)continue;const key=(f.fileName||'').trim().toLowerCase();if(key&&!map.has(key))map.set(key,f);}return [...map.values()];}
async function uploadOneLocalFile(f){if(!cloudUser||!f?.id||!f?.blob)return false;const dbName=CLOUD_DATABASES.includes(f.sourceDb)?f.sourceDb:'RH_PRO_DOCUMENTOS';const path=cloudUser.id+'/'+dbName+'/'+encodeURIComponent(String(f.id));const {error}=await cloudDb.storage.from('rhpro-files').upload(path,f.blob,{contentType:f.blob.type||f.mimeType||'application/octet-stream',upsert:true});if(error){console.error('RH PRO upload discovered',f.fileName,error);return false;}const {error:metaError}=await cloudDb.from('rhpro_files').upsert({user_id:cloudUser.id,file_id:String(f.id),storage_path:path,file_name:f.fileName||f.nome||f.name||String(f.id),mime_type:f.blob.type||f.mimeType||null,file_size:f.blob.size||null},{onConflict:'user_id,file_id'});if(metaError){console.error('RH PRO metadata discovered',f.fileName,metaError);return false;}return true;}
async function cloudRecoverLegacyFiles(){if(!cloudUser)return 0;const files=await discoverAllLocalFiles();let sent=0;for(const f of files){if(await uploadOneLocalFile(f))sent++;}return sent;}
async function cloudUploadLocal(){if(!cloudUser)return 0;let sent=0;for(const dbName of CLOUD_DATABASES){const files=await allLocalFiles(dbName);for(const f of files){if(!f?.id||!f?.blob)continue;const path=cloudUser.id+'/'+dbName+'/'+encodeURIComponent(String(f.id));const {error}=await cloudDb.storage.from('rhpro-files').upload(path,f.blob,{contentType:f.blob.type||f.mimeType||'application/octet-stream',upsert:true});if(error){console.error('RH PRO upload',dbName,f.id,error);continue;}const fileId=String(f.id);const {error:metaError}=await cloudDb.from('rhpro_files').upsert({user_id:cloudUser.id,file_id:fileId,storage_path:path,file_name:f.fileName||f.nome||f.name||f.blob.name||fileId,mime_type:f.blob.type||f.mimeType||null,file_size:f.blob.size||null},{onConflict:'user_id,file_id'});if(metaError){console.error('RH PRO metadata',dbName,f.id,metaError);continue;}sent++;}}return sent;}
async function cloudDownloadRemote(){if(!cloudUser)return 0;const {data,error}=await cloudDb.from('rhpro_files').select('file_id,storage_path,file_name,mime_type').eq('user_id',cloudUser.id);if(error){console.error('RH PRO list cloud files',error);return 0;}if(!data?.length)return 0;const localMap=new Map();for(const dbName of CLOUD_DATABASES){const local=await allLocalFiles(dbName);for(const f of local){if(f?.id)localMap.set(dbName+'::'+String(f.id),f);}}let got=0;for(const row of data){if(!row?.file_id||!row?.storage_path)continue;const dbName=databaseForFile(row.storage_path);const key=dbName+'::'+String(row.file_id);if(localMap.get(key)?.blob)continue;const {data:blob,error:dlErr}=await cloudDb.storage.from('rhpro-files').download(row.storage_path);if(dlErr||!blob){console.error('RH PRO download',row.file_id,dlErr);continue;}const ok=await putLocalFile(dbName,{id:String(row.file_id),blob,fileName:row.file_name,nome:row.file_name,area:'Nuvem RH PRO',mimeType:row.mime_type||blob.type});if(ok)got++;}return got;}
async function findLocalFileByName(fileName){const target=String(fileName||'').trim().toLowerCase();if(!target)return null;for(const dbName of CLOUD_DATABASES){const files=await allLocalFiles(dbName);const found=files.find(f=>String(f?.fileName||f?.nome||f?.name||f?.blob?.name||'').trim().toLowerCase()===target);if(found?.blob)return found;}const discovered=await discoverAllLocalFiles();return discovered.find(f=>String(f?.fileName||f?.nome||f?.name||'').trim().toLowerCase()===target)||null;}
async function openRhProCloudFile(fileName){try{const target=String(fileName||'').trim();let found=await findLocalFileByName(target);if(found?.blob){const uploaded=await uploadOneLocalFile(found);const url=URL.createObjectURL(found.blob);window.open(url,'_blank','noopener');setTimeout(()=>URL.revokeObjectURL(url),120000);return uploaded||true;}if(!cloudUser)return false;const {data,error}=await cloudDb.from('rhpro_files').select('file_id,storage_path,file_name,mime_type').eq('user_id',cloudUser.id).eq('file_name',target);if(error||!data?.length)return false;const row=data[0];const {data:blob,error:dlErr}=await cloudDb.storage.from('rhpro-files').download(row.storage_path);if(dlErr||!blob)return false;const dbName=databaseForFile(row.storage_path);await putLocalFile(dbName,{id:String(row.file_id),blob,fileName:row.file_name,nome:row.file_name,area:'Nuvem RH PRO',mimeType:row.mime_type||blob.type});const url=URL.createObjectURL(blob);window.open(url,'_blank','noopener');setTimeout(()=>URL.revokeObjectURL(url),120000);return true;}catch(e){console.error('RH PRO open cloud file',fileName,e);return false;}}
function installUniversalDocumentOpener(){const iframe=document.getElementById('app');if(!iframe)return;const install=()=>{try{const doc=iframe.contentDocument;if(!doc)return;doc.documentElement.dataset.rhProOpenFix='3';doc.addEventListener('click',async ev=>{const btn=ev.target?.closest?.('button,a');if(!btn)return;const label=String(btn.textContent||'').trim().toLowerCase();if(!label.includes('abrir'))return;const row=btn.closest('tr');if(!row)return;const cells=[...row.querySelectorAll('td')];const fileCell=cells.find(td=>isFileName(td.textContent.trim()));const fileName=fileCell?.textContent?.trim();if(!fileName)return;ev.preventDefault();ev.stopImmediatePropagation();const ok=await openRhProCloudFile(fileName);if(!ok)alert('Arquivo não encontrado no armazenamento local ou na nuvem.');},true);}catch(e){console.error('RH PRO opener install',e);}};iframe.addEventListener('load',install);setTimeout(install,500);setTimeout(install,1500);}
async function cloudCycle(){if(!cloudUser||cloudBusy)return;cloudBusy=true;try{cloudStatus('☁ Verificando e protegendo documentos...');const recovered=await cloudRecoverLegacyFiles();const sent=await cloudUploadLocal();const got=await cloudDownloadRemote();cloudStatus((recovered||sent||got)?'☁ Documentos sincronizados':'☁ Sincronizado');}catch(e){console.error('RH PRO cloud files',e);cloudStatus('⚠ Erro nos documentos');}finally{cloudBusy=false;}}
async function cloudStart(){if(cloudUser)return;try{const {data}=await cloudDb.auth.getSession();if(!data?.session)return;cloudUser=data.session.user;installUniversalDocumentOpener();await cloudCycle();if(cloudTimer)clearInterval(cloudTimer);cloudTimer=setInterval(cloudCycle,8000);}catch(e){console.error('RH PRO cloud start',e);}}
setInterval(()=>{if(!cloudUser)cloudStart();},2000);cloudStart();
