const CLOUD_SUPABASE_URL='https://ydqqxvtfvnhxpydccciu.supabase.co';
const CLOUD_SUPABASE_KEY='sb_publishable_A-x4W6e_ES8k7fQR3TgGhw_DeVLH50O';
const cloudDb=window.supabase.createClient(CLOUD_SUPABASE_URL,CLOUD_SUPABASE_KEY);
const CLOUD_DATABASES=['RH_PRO_DOCUMENTOS','RH_PRO_TREINAMENTOS'];
let cloudUser=null,cloudBusy=false,cloudTimer=null;
const cloudStatus=msg=>{const el=document.getElementById('sync');if(el&&msg)el.textContent=msg;};
function openLocalFilesDB(name='RH_PRO_DOCUMENTOS'){return new Promise((resolve,reject)=>{const req=indexedDB.open(name);req.onsuccess=()=>{const db=req.result;if(!db.objectStoreNames.length){db.close();reject(new Error('Armazenamento indisponível.'));return;}resolve({db,stores:[...db.objectStoreNames]});};req.onerror=()=>reject(req.error||new Error('Não foi possível abrir documentos locais.'));});}
async function allStoreRows(db,storeName){return await new Promise(resolve=>{try{const tx=db.transaction(storeName,'readonly'),r=tx.objectStore(storeName).getAll();r.onsuccess=()=>resolve(r.result||[]);r.onerror=()=>resolve([]);}catch(e){resolve([]);}});}
function isFileName(name=''){return /\.(pdf|jpg|jpeg|png|gif|webp|doc|docx|xls|xlsx|txt|csv|zip)$/i.test(String(name||''));}
function dataToBlob(raw,mime='application/octet-stream'){
  if(!raw)return null;
  if(raw instanceof Blob)return raw;
  if(raw instanceof ArrayBuffer)return new Blob([raw],{type:mime});
  if(ArrayBuffer.isView(raw))return new Blob([raw.buffer],{type:mime});
  if(typeof raw==='string'){
    const s=raw.trim();
    if(s.startsWith('data:')){try{const [head,b64]=s.split(',');const mt=(head.match(/^data:([^;]+)/)||[])[1]||mime;const bin=atob(b64||'');const bytes=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)bytes[i]=bin.charCodeAt(i);return new Blob([bytes],{type:mt});}catch(e){return null;}}
    if(/^[A-Za-z0-9+/=\r\n]+$/.test(s)&&s.length>200){try{const bin=atob(s.replace(/\s/g,''));const bytes=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)bytes[i]=bin.charCodeAt(i);return new Blob([bytes],{type:mime});}catch(e){}}
  }
  return null;
}
function firstFileLike(value,mime='application/octet-stream',seen=new Set(),depth=0){
  if(value==null||depth>5)return null;
  if(value instanceof Blob)return value;
  if(value instanceof ArrayBuffer)return new Blob([value],{type:mime});
  if(ArrayBuffer.isView(value))return new Blob([value.buffer],{type:mime});
  if(typeof value==='string')return dataToBlob(value,mime);
  if(typeof value!=='object')return null;
  if(seen.has(value))return null;seen.add(value);
  const preferred=['blob','file','arquivoBlob','fileBlob','dataUrl','dataURL','base64','content','arquivo','anexo','attachment','documento','document'];
  for(const k of preferred)if(k in value){const b=firstFileLike(value[k],value.mimeType||value.mime_type||value.type||mime,seen,depth+1);if(b)return b;}
  for(const k of Object.keys(value)){if(preferred.includes(k))continue;const v=value[k];if(typeof v==='object'||typeof v==='string'){const b=firstFileLike(v,value.mimeType||value.mime_type||value.type||mime,seen,depth+1);if(b)return b;}}
  return null;
}
function findNameInObject(rec){if(!rec||typeof rec!=='object')return '';const keys=['fileName','filename','nomeArquivo','nome','name','file_name','arquivo','documento'];for(const k of keys){const v=rec[k];if(typeof v==='string'&&isFileName(v.trim()))return v.trim();}return '';}
function normalizeFileRecord(rec,sourceDb='',sourceStore=''){
  if(!rec||typeof rec!=='object')return null;
  const name=findNameInObject(rec);
  const id=String(rec.id??rec.fileId??rec.file_id??rec.documentId??rec.document_id??rec.chave??'').trim();
  const mime=rec.mimeType||rec.mime_type||rec.type||'application/octet-stream';
  const blob=firstFileLike(rec,mime);
  if(!name||!blob)return null;
  return {id:id||('legacy_'+btoa(unescape(encodeURIComponent(sourceDb+'|'+sourceStore+'|'+name))).replace(/[^a-zA-Z0-9_-]/g,'').slice(0,80)),blob,fileName:name,nome:name,mimeType:blob.type||mime,sourceDb,sourceStore};
}
async function allLocalFiles(name){try{const {db,stores}=await openLocalFilesDB(name);const out=[];for(const store of stores)for(const rec of await allStoreRows(db,store)){const n=normalizeFileRecord(rec,name,store);if(n)out.push(n);}db.close();return out;}catch(e){return[];}}
async function getLocalFileById(dbName,id){const target=String(id??'').trim();if(!target)return null;try{const {db,stores}=await openLocalFilesDB(dbName);for(const storeName of stores)for(const rec of await allStoreRows(db,storeName)){const rid=String(rec?.id??rec?.fileId??rec?.file_id??rec?.documentId??rec?.document_id??rec?.chave??'').trim();if(rid===target){const n=normalizeFileRecord(rec,dbName,storeName);if(n){db.close();return n;}}}db.close();}catch(e){}return null;}
async function putLocalFile(name,rec){if(!rec?.id||!rec?.blob)return false;try{const {db}=await openLocalFilesDB(name);let storeName=db.objectStoreNames.contains('files')?'files':db.objectStoreNames[0];const tx=db.transaction(storeName,'readwrite');tx.objectStore(storeName).put(rec);return await new Promise(resolve=>{tx.oncomplete=()=>{db.close();resolve(true)};tx.onerror=()=>{db.close();resolve(false)};tx.onabort=()=>{db.close();resolve(false)};});}catch(e){return false;}}
function databaseForFile(storagePath=''){const parts=String(storagePath||'').split('/');return parts.length>=3?decodeURIComponent(parts[1]):'RH_PRO_DOCUMENTOS';}
async function discoverIndexedDbFiles(){const out=[];try{if(typeof indexedDB.databases!=='function')return out;for(const info of await indexedDB.databases()){const name=String(info?.name||'');if(!name)continue;for(const f of await allLocalFiles(name))out.push(f);}}catch(e){}return out;}
async function discoverDataReferencedFiles(){const out=[];try{const keys=[];for(let i=0;i<localStorage.length;i++)keys.push(localStorage.key(i));for(const key of keys){let raw='';try{raw=localStorage.getItem(key)||''}catch(e){}if(!raw||raw.length<20)continue;let data;try{data=JSON.parse(raw)}catch(e){continue}const walk=async(value,path='')=>{if(value==null||typeof value!=='object')return;if(Array.isArray(value)){for(const v of value)await walk(v,path);return;}const name=findNameInObject(value);if(name){const blob=firstFileLike(value);if(blob)out.push({id:String(value.id??value.fileId??value.file_id??value.documentId??'').trim()||('legacy_ls_'+btoa(unescape(encodeURIComponent(key+'|'+path+'|'+name))).replace(/[^a-zA-Z0-9_-]/g,'').slice(0,80)),blob,fileName:name,nome:name,mimeType:blob.type||value.mimeType||value.mime_type||'application/octet-stream',sourceDb:'RH_PRO_DOCUMENTOS',sourceStore:'localStorage'});}for(const [k,v] of Object.entries(value)){if(typeof v==='object')await walk(v,path+'/'+k)}};await walk(data)}}catch(e){}return out;}
async function discoverAllLocalFiles(){const a=await discoverIndexedDbFiles(),b=await discoverDataReferencedFiles(),map=new Map();for(const f of [...a,...b]){if(!f?.blob||!f?.fileName)continue;const key=f.fileName.trim().toLowerCase();if(!map.has(key))map.set(key,f);}return [...map.values()];}
async function uploadOneLocalFile(f){if(!cloudUser||!f?.id||!f?.blob)return false;const dbName=CLOUD_DATABASES.includes(f.sourceDb)?f.sourceDb:'RH_PRO_DOCUMENTOS',path=cloudUser.id+'/'+dbName+'/'+encodeURIComponent(String(f.id));const {error}=await cloudDb.storage.from('rhpro-files').upload(path,f.blob,{contentType:f.blob.type||f.mimeType||'application/octet-stream',upsert:true});if(error)return false;const {error:metaError}=await cloudDb.from('rhpro_files').upsert({user_id:cloudUser.id,file_id:String(f.id),storage_path:path,file_name:f.fileName||f.nome||String(f.id),mime_type:f.blob.type||f.mimeType||null,file_size:f.blob.size||null},{onConflict:'user_id,file_id'});return !metaError;}
async function cloudRecoverLegacyFiles(){if(!cloudUser)return 0;let sent=0;for(const f of await discoverAllLocalFiles())if(await uploadOneLocalFile(f))sent++;return sent;}
async function cloudUploadLocal(){if(!cloudUser)return 0;let sent=0;for(const dbName of CLOUD_DATABASES)for(const f of await allLocalFiles(dbName)){if(await uploadOneLocalFile({...f,sourceDb:dbName}))sent++;}return sent;}
async function cloudDownloadRemote(){if(!cloudUser)return 0;const {data,error}=await cloudDb.from('rhpro_files').select('file_id,storage_path,file_name,mime_type').eq('user_id',cloudUser.id);if(error||!data?.length)return 0;let got=0;for(const row of data){if(!row?.file_id||!row?.storage_path)continue;const dbName=databaseForFile(row.storage_path),local=await getLocalFileById(dbName,row.file_id);if(local?.blob)continue;const {data:blob,error:dlErr}=await cloudDb.storage.from('rhpro-files').download(row.storage_path);if(dlErr||!blob)continue;if(await putLocalFile(dbName,{id:String(row.file_id),blob,fileName:row.file_name,nome:row.file_name,area:'Nuvem RH PRO',mimeType:row.mime_type||blob.type}))got++;}return got;}
async function findLocalFileByName(fileName){const target=String(fileName||'').trim().toLowerCase();if(!target)return null;const all=await discoverAllLocalFiles();const found=all.find(f=>String(f.fileName||'').trim().toLowerCase()===target);return found?.blob?found:null;}
async function openRhProCloudFile(fileName){try{const target=String(fileName||'').trim(),found=await findLocalFileByName(target);if(found?.blob){await uploadOneLocalFile(found);const url=URL.createObjectURL(found.blob);window.open(url,'_blank','noopener');setTimeout(()=>URL.revokeObjectURL(url),120000);return true;}if(!cloudUser)return false;const {data,error}=await cloudDb.from('rhpro_files').select('file_id,storage_path,file_name,mime_type').eq('user_id',cloudUser.id).eq('file_name',target);if(error||!data?.length)return false;const row=data[0],dl=await cloudDb.storage.from('rhpro-files').download(row.storage_path);if(dl.error||!dl.data)return false;const dbName=databaseForFile(row.storage_path);await putLocalFile(dbName,{id:String(row.file_id),blob:dl.data,fileName:row.file_name,nome:row.file_name,area:'Nuvem RH PRO',mimeType:row.mime_type||dl.data.type});const url=URL.createObjectURL(dl.data);window.open(url,'_blank','noopener');setTimeout(()=>URL.revokeObjectURL(url),120000);return true;}catch(e){console.error('RH PRO open cloud file',fileName,e);return false;}}
function installUniversalDocumentOpener(){const iframe=document.getElementById('app');if(!iframe)return;const install=()=>{try{const doc=iframe.contentDocument;if(!doc)return;doc.documentElement.dataset.rhProOpenFix='7';if(doc.documentElement.dataset.rhProOpenListener==='1')return;doc.documentElement.dataset.rhProOpenListener='1';doc.addEventListener('click',async ev=>{const btn=ev.target?.closest?.('button,a');if(!btn)return;const inline=String(btn.getAttribute('onclick')||'');if(/viewDocument\s*\(/i.test(inline))return;const label=String(btn.textContent||'').trim().toLowerCase();if(!label.includes('abrir'))return;const row=btn.closest('tr');if(!row)return;const cells=[...row.querySelectorAll('td')],fileCell=cells.find(td=>isFileName(td.textContent.trim())),fileName=fileCell?.textContent?.trim();if(!fileName)return;ev.preventDefault();ev.stopImmediatePropagation();const ok=await openRhProCloudFile(fileName);if(!ok)alert('Arquivo não encontrado no armazenamento local ou na nuvem.');},true);}catch(e){console.error('RH PRO opener install',e);}};iframe.addEventListener('load',install);setTimeout(install,500);setTimeout(install,1500);setTimeout(install,3000);}
async function cloudCycle(){if(!cloudUser||cloudBusy)return;cloudBusy=true;try{cloudStatus('☁ Recuperando documentos antigos...');const recovered=await cloudRecoverLegacyFiles(),sent=await cloudUploadLocal(),got=await cloudDownloadRemote();cloudStatus((recovered||sent||got)?'☁ Documentos sincronizados':'☁ Sincronizado');}catch(e){console.error('RH PRO cloud files',e);cloudStatus('⚠ Erro nos documentos');}finally{cloudBusy=false;}}
async function cloudStart(){if(cloudUser)return;try{const {data}=await cloudDb.auth.getSession();if(!data?.session)return;cloudUser=data.session.user;installUniversalDocumentOpener();await cloudCycle();if(cloudTimer)clearInterval(cloudTimer);cloudTimer=setInterval(cloudCycle,8000);}catch(e){console.error('RH PRO cloud start',e);}}
setInterval(()=>{if(!cloudUser)cloudStart();},2000);cloudStart();
