const SUPABASE_URL='https://ydqqxvtfvnhxpydccciu.supabase.co';
const SUPABASE_KEY='sb_publishable_A-x4W6e_ES8k7fQR3TgGhw_DeVLH50O';
const db=supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
const frame=document.getElementById('app');const login=document.getElementById('login');const statusEl=document.getElementById('status');const syncEl=document.getElementById('sync');
let user=null,lastHash='',lastRemoteUpdated='',syncing=false,applying=false;
function status(msg,cls=''){statusEl.className=cls;statusEl.textContent=msg}
function frameStorage(){try{return frame.contentWindow.localStorage}catch(e){return null}}
function snapshot(){const s=frameStorage();if(!s)return {};const data=s.getItem('RH_PRO_DATA');return data?{RH_PRO_DATA:data}:{}}
function dataFromSnap(s){try{return s?.RH_PRO_DATA?JSON.parse(s.RH_PRO_DATA):null}catch(e){return null}}
function collaboratorCount(s){const d=dataFromSnap(s);return Array.isArray(d?.Colaboradores)?d.Colaboradores.length:0}
function hash(s){return JSON.stringify(s)}
function putSnapshot(s){const st=frameStorage();if(!st||!s?.RH_PRO_DATA)return false;applying=true;try{st.setItem('RH_PRO_DATA',s.RH_PRO_DATA)}finally{applying=false}return true}
async function readRemote(){if(!user)return null;const {data,error}=await db.from('rhpro_sync').select('data,updated_at').eq('user_id',user.id).maybeSingle();if(error){console.error(error);syncEl.textContent='⚠ Falha na leitura';return null}return data||null}
async function saveRemote(force=false){if(!user||applying||syncing)return false;const snap=snapshot();const h=hash(snap);if(!force&&h===lastHash)return true;syncing=true;try{const now=new Date().toISOString();const {error}=await db.from('rhpro_sync').upsert({user_id:user.id,data:snap,updated_at:now},{onConflict:'user_id'});if(error){console.error(error);syncEl.textContent='⚠ Erro ao sincronizar';return false}lastHash=h;lastRemoteUpdated=now;syncEl.textContent='☁ Sincronizado';return true}finally{syncing=false}}
async function initialSync(){syncEl.textContent='☁ Verificando sincronização...';await new Promise(r=>setTimeout(r,700));const local=snapshot();const remote=await readRemote();if(!remote||!remote.data||!remote.data.RH_PRO_DATA){lastHash=hash(local);await saveRemote(true);return}const lc=collaboratorCount(local),rc=collaboratorCount(remote.data);if(lc>rc){syncEl.textContent='☁ Preservando os dados deste aparelho...';lastHash='';await saveRemote(true);return}if(rc>lc){putSnapshot(remote.data);lastHash=hash(remote.data);lastRemoteUpdated=remote.updated_at||'';syncEl.textContent='☁ Dados recuperados da nuvem';setTimeout(()=>frame.contentWindow.location.reload(),100);return}const rh=hash(remote.data),lh=hash(local);if(rh!==lh){putSnapshot(remote.data);lastHash=rh;lastRemoteUpdated=remote.updated_at||'';syncEl.textContent='☁ Dados sincronizados';setTimeout(()=>frame.contentWindow.location.reload(),100)}else{lastHash=lh;lastRemoteUpdated=remote.updated_at||'';syncEl.textContent='☁ Sincronizado'}}
async function checkRemote(){if(!user||applying||syncing)return;const local=snapshot(),lh=hash(local);if(lh!==lastHash){await saveRemote(false);return}const remote=await readRemote();if(!remote?.data?.RH_PRO_DATA)return;const rh=hash(remote.data);if(rh===lastHash){lastRemoteUpdated=remote.updated_at||lastRemoteUpdated;return}const lc=collaboratorCount(local),rc=collaboratorCount(remote.data);if(lc>rc){await saveRemote(true);return}putSnapshot(remote.data);lastHash=rh;lastRemoteUpdated=remote.updated_at||'';syncEl.textContent='☁ Atualização recebida';setTimeout(()=>frame.contentWindow.location.reload(),100)}
async function startSync(){if(!user)return;login.style.display='none';syncEl.style.display='block';await initialSync();setInterval(checkRemote,4000)}
document.getElementById('enter').onclick=async()=>{const email=document.getElementById('email').value.trim(),password=document.getElementById('password').value;if(!email||!password){status('Informe e-mail e senha.','err');return}status('Entrando...');const {data,error}=await db.auth.signInWithPassword({email,password});if(error){status('Não foi possível entrar: '+error.message,'err');return}user=data.user;status('Acesso autorizado.','ok');startSync()};
document.getElementById('signup').onclick=async()=>{const email=document.getElementById('email').value.trim(),password=document.getElementById('password').value;if(!email||password.length<6){status('Informe um e-mail e uma senha com pelo menos 6 caracteres.','err');return}status('Criando acesso...');const {data,error}=await db.auth.signUp({email,password,options:{emailRedirectTo:location.href}});if(error){status('Não foi possível criar o acesso: '+error.message,'err');return}if(data.session){user=data.user;startSync()}else status('Acesso criado. Confirme o e-mail e depois entre no sistema.','ok')};
document.getElementById('forgot').onclick=async()=>{const email=document.getElementById('email').value.trim();if(!email){status('Digite seu e-mail primeiro.','err');return}const {error}=await db.auth.resetPasswordForEmail(email,{redirectTo:location.href});status(error?'Não foi possível enviar: '+error.message:'Enviamos o link de recuperação para seu e-mail.',error?'err':'ok')};
document.getElementById('resend').onclick=async()=>{const email=document.getElementById('email').value.trim();if(!email){status('Digite seu e-mail primeiro.','err');return}const {error}=await db.auth.resend({type:'signup',email,options:{emailRedirectTo:location.href}});status(error?'Não foi possível reenviar: '+error.message:'Confirmação reenviada. Verifique também o spam.',error?'err':'ok')};
window.addEventListener('load',async()=>{const {data}=await db.auth.getSession();if(data.session){user=data.session.user;startSync()}});db.auth.onAuthStateChange((event,session)=>{if(event==='SIGNED_IN'&&session&&!user){user=session.user;startSync()}});